apiVersion: apps/v1
kind: Deployment
metadata:
  name: benjamintoll
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: benjamintoll
        image: btoll/benjamintoll.com:latest
        env:
          - name: SECRET
            value: dawg
          - name: BAG
            value: wank
          - name: MESSAGE
            value: This is a bag of $(BAG)
        envFrom:
          - configMapRef:
              name: env
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443

