apiVersion: apps/v1
kind: Deployment
metadata:
  name: benjamintoll
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: benjamintoll
        image: btoll/benjamintoll.com:latest
        envFrom:
          - configMapRef:
              name: envs
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443

